export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_INVALID_CREDENTIALS = 'SET_INVALID_CREDENTIALS';

export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
